---

# Brew.
- name: Define brew_upgrade_all_packages
  set_fact:
    brew_upgrade_all_packages: "{{ brew.upgrade_all_packages }}"
  when: brew_upgrade_all_packages is undefined

- name: Define brew_packages.
  set_fact:
    brew_packages: "{{ brew.packages | list }}"
  when: brew_packages is undefined

- name: Define brew_blacklists.
  set_fact:
    brew_blacklists: "{{ brew.blacklists | list }}"
  when: brew_blacklists is undefined

- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items: "{{ brew_packages }}"

- name: Ensure blacklisted homebrew packages are not installed.
  homebrew: "name={{ item }} state=absent"
  with_items: "{{ brew_blacklists }}"

- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: brew_upgrade_all_packages
