---

- name: Check for Brewfile.
  stat:
    path: "{{ homebrew.brewfile_dir }}/Brewfile"
  register: homebrew.brewfile

- name: Install from Brewfile.
  command: "brew bundle chdir={{ homebrew.brewfile_dir }}"
  when: homebrew.brewfile.stat.exists and brew_use_brewfile
