---


- name: Define brew_casks_packages.
  set_fact:
    brew_casks_packages: "{{ brew.casks.packages | list }}"
  when: brew_casks_packages is undefined

- name: Define brew_casks_blacklists.
  set_fact:
    brew_casks_blacklists: "{{ brew.casks.blacklists | list }}"
  when: brew_casks_blacklists is undefined

# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
    - caskroom/cask

# Cask.
- name: Install configured cask applications.
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew.casks.appdir }}"
  with_items: "{{ brew_casks_packages }}"

- name: Ensure blacklisted cask applications are not installed.
  homebrew_cask: "name={{ item }} state=absent"
  with_items: "{{ brew_casks_blacklists }}"
