---

brew_upgrade_all_packages: no

brew_packages:
  - ssh-copy-id
  - pv
  - brew-cask
  - ant
  - gradle
  - maven-deluxe
  - node
  - tomcat
  - eclipse-java
  - openshift-cli
  - bash-completion
  - docker-completion
  - docker-compose-completion
  - docker-machine-completion

brew_blacklists: []

brew_use_brewfile: no
brew_brewfile_dir: "{{playbook_dir}}"

brew_taps:
  - homebrew/core
  - caskroom/cask
  - jcgay/jcgay

brew_casks_packages:
  - adobe-acrobat-reader
  - firefox
  - chromium
  - minishift
  - intellij-idea
  - intellij-idea-ce
  - atom
  - sublime-text
  - slack
  - sqlectron
  - vagrant
  - virtualbox
  - vagrant-manager
  - docker

  brew_casks_blacklists: []
